Add support for ldoc globals builtin
lunarmodules/luacheck pull request #71
Opened 2022-07-04 18:30 UTC by Aire-One

This adds initial support for the ldoc global builtin fields and functions as listed at https://github.com/lunarmodules/LDoc/blob/38b1537d1fa78fcf11668d2f1dd556fec8c417c8/doc/doc.md#fields-allowed-in-configld.

I think this is useful for luacheck, because it allows to include any ldoc `config.ld` file to be linted by luacheck easily.

Currently, we need to manually declare (or ignore) to luacheck each builtin field used in a ldoc configuration file.  With this new builtin_standards, the user can simply add `files["path/to/config.ld"].std = "+ldoc"` to their `.luacheckrc` and they are done.

2022-07-04 19:14 UTC, alerque requested changes
Thanks for taking the time to contribute these, it looks like a useful set to add to me!

First, it looks like you missed a few, particularly where more than one is mentioned on the same line in the docks: I spotted `template` and `topics`, but then I stopped looking so there may be more.

Second, we should look around for where the right place to document this is. The PR has a nice note on how to use it, but we should get that in documentation wherever other builtins are explained.

2022-07-04 22:19 UTC, Aire-One commented
Thank you for your review @alerque!

> First, it looks like you missed a few, particularly where more than one is mentioned on the same line in the docks: I spotted template and topics, but then I stopped looking so there may be more.

Oops, I have blindly selected the first word of each bullet point...

Note that I'm in the process of double-checking everything. It seems like the documentation I linked doesn't list all the available fields. I'm double-checking whether I haven't missed more... I'll come back to you later to confirm I'm done.

> Second, we should look around for where the right place to document this is. The PR has a nice note on how to use it, but we should get that in documentation wherever other builtins are explained.

I think I have added the necessary mention in the documentation now.

I also took the liberty to make it a default for `config.ld` files. Please confirm this is ok by you.

2022-07-08 18:00 UTC, alerque approved these changes

2022-07-08 18:03 UTC, Aire-One commented
@alerque, I think everything is ready now. I'm waiting for your next review/feedback :smile: 

Note: I have completed the "undocumented fields" with fields randomly mentioned in the page https://stevedonovan.github.io/ldoc/manual/doc.md.html, and from the table https://github.com/lunarmodules/LDoc/blob/147951025b6e55017c338c2d763bcc722f44bd6a/ldoc.lua#L243-L256.

2022-07-08 18:08 UTC, merged

2022-07-08 18:09 UTC, alerque commented
Looks good to me! Thanks for the contribution. I won't be around for a week or so and hence this won't get a tagged release any time *very* soon, but there isn't really much holding that up other than some testing and minor release management issues.

2022-07-08 18:12 UTC, Aire-One commented
> Looks good to me! Thanks for the contribution. I won't be around for a week or so and hence this won't get a tagged release any time _very_ soon, but there isn't really much holding that up other than some testing and minor release management issues.

Cool, thank you for the information.