Update index.rst
lunarmodules/luacheck pull request #82
Opened 2022-11-20 19:09 UTC by muescha

update version number to 1.0.0

2022-11-20 19:12 UTC, muescha commented
- used static text at first (01849a126e604d1094fe0283102ecdccce83c1b8)
- then changed to variable (1005f75d27c752ba42fccbd0a097db4ccf58ef83) - but i don't know if a variable works

2022-11-28 23:41 UTC, arichard4 commented
I don't think that the variable works. I tested locally with sphinx-build and it output the text "{{ version }}". Let me investigate further, the variable approach would be nice; however, readthedocs.io, the most frequent place the docs are stored, mentions the version beside the docs, so we can just remove that if needed.

2022-11-28 23:55 UTC, arichard4 commented
@muescha According to the [sphinx docs](https://sphinx-doc-zh.readthedocs.io/en/latest/markup/inline.html#other-semantic-markup), you can insert the version with "|version|". While you're here, please move the version number to be after the word version. The can be tested with "sphinx docsrc doc", and then opening doc/index.html

2022-11-28 23:56 UTC, arichard4 requested changes
Pls change to "version |version|"

2022-11-29 06:08 UTC, alerque commented on docsrc/index.rst
> +This is documentation for {{ version }} version of `Luacheck <https://github.com/lunarmodules/luacheck/>`_, a linter for `Lua <https://www.lua.org/>`_.
```suggestion
This is documentation for version |version| of `Luacheck <https://github.com/lunarmodules/luacheck/>`_, a linter for `Lua <https://www.lua.org/>`_.
```

2022-11-29 06:11 UTC, alerque approved these changes
Thanks for catching this and taking the time to contribute. I tested @arichard4's suggested variable version locally and it seems to work, so went ahead and ammended this PR with that info. Thanks to both of you for tracking that down.

2022-11-29 06:22 UTC, merged