build: add luarocks.lock
lunarmodules/luacheck pull request #83
Opened 2022-12-08 20:38 UTC by chenrui333

Lockfile is a way to ensure [the repeatable build](https://github.com/luarocks/luarocks/wiki/Pinning-versions-with-a-lock-file), thus adding the lockfile and update make builds to use `--pin`

also relates to https://github.com/Homebrew/homebrew-core/pull/117684

2022-12-09 08:53 UTC, alerque commented on .github/workflows/luacheck.yml
> +        run: luarocks make --pin
```suggestion
        run: luarocks make
```

This CI job can't make use of pinned dependencies because we test across an array of Lua versions.

2022-12-09 18:10 UTC, alerque requested changes

2022-12-09 18:12 UTC, alerque commented
I wonder if we should add Lua support to [`updlockfiles`](https://github.com/kpcyrd/updlockfiles) and whether Homebrew could use that (or something like it) to pin dependencies only in their builds. In that case having the VM an everything always pinned would make sense and make the builds reproducible.

Note this package is built reproducibly on other distros already without a lock file, but since the distro supplies the dependencies not LuaRocks vendoring the inputs are known and external to the package.

2022-12-13 02:35 UTC, closed without merging

2022-12-13 02:35 UTC, chenrui333 commented
I dont think it works as I anticipated, closing this PR for now, we can revisit it later.